import turtle as t
import random

t.speed(0)
t.bgcolor("dark blue")
t.penup()
t.goto(-700, -200)
t.pendown()
t.color("black")
t.fillcolor("green")
t.begin_fill()
def grond():
    for i in range(4):
        t.fd(1400)
        t.rt(90)
grond()
t.end_fill()

t.penup()
t.goto(-400, -200)
t.pendown()
t.lt(90)
def vierkant(grootte):
    for i in range(4):
        t.fd(grootte)
        t.rt(90)

t.penup()
xwater = random.randint(200, 300)
t.goto(xwater ,-400)
def water(grootte, kleur):
    t.color("black")
    t.fillcolor(kleur)
    t.begin_fill()
    vierkant(grootte)
    t.end_fill()
water(200, "blue")

t.pu()
t.goto(900, -200)
t.pd()
t.seth(0)
def berg(grootte):
    for i in range(3):
        t.lt(120)
        t.fd(grootte)
t.pensize(5)
t.fillcolor("gray")
t.begin_fill()
def meerderebergen(grootte):
    for i in range(5):
        berg(grootte)
        t.backward(300)
meerderebergen(500)
t.end_fill()

t.pensize(5)
t.penup()
xsterretje = random.randint(-100, 400)
t.goto(xsterretje, 300)
t.pendown()
def sterretje(grootte, kleur, hoek):
    t.color("yellow")
    t.fillcolor(kleur)
    t.begin_fill()
    for i in range(5):
        t.forward(grootte)
        t.right(hoek)
        t.forward(grootte)
        t.right(72 - hoek)
    t.end_fill()
sterretje(15, "yellow", 120)

for i in range(4):
    sterretje(15, "yellow", 120)
    t.penup()
    t.rt(90)
    t.fd(100)
    t.pendown()

t.pensize(0)
t.penup()
t.goto(-350, 200)
t.pendown()
#eclipse 
def eclipse(grootte):
    t.color("black")
    t.fillcolor("white")
    t.begin_fill()
    t.circle(grootte)
    t.end_fill()
eclipse(53)

t.penup()
t.goto(-350, 190)
t.pendown()
t.color("black")
t.fillcolor("orange")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
xhuis = random.randint(-220, 0)
t.goto(xhuis, -200)
t.pendown()
t.seth(90)
def huis():
    t.color("black")
    t.fillcolor("red")
    t.begin_fill()
    vierkant(100)
    t.end_fill()
    t.rt(90)
    t.fd(25)
    t.lt(90)
    t.fillcolor("blue")
    t.begin_fill()
    vierkant(50)
    t.end_fill()
    t.penup()
    t.fd(100)
    t.lt(90)
    t.fd(25)
    t.pendown()
    t.fillcolor("green")
    t.begin_fill()
    for i in range(3):
        t.rt(120)
        t.fd(100)
    t.end_fill()
    t.penup()
    t.backward(65)
    t.rt(90)
    t.fd(15)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    for i in range(4):
        t.fd(30)
        t.lt(90)
    t.end_fill()
    t.fillcolor("black")
    t.begin_fill()
    for i in range(4):
        t.fd(15)
        t.lt(90)
    t.end_fill()
    t.fillcolor("blue")
    t.begin_fill()
    t.fd(15)
    for i in range(4):
        t.fd(15)
        t.lt(90)
    t.end_fill()
    t.lt(90)
    t.fd(15)
    t.fillcolor("white")
    t.begin_fill()
    for i in range(4):
        t.fd(15)
        t.lt(90)
    t.end_fill()
    t.penup()
    t.fd(40)
    t.lt(90)
    t.fd(40)
    t.pendown()
    t.fd(25)
    t.backward(12.5)
    t.lt(90)
    t.fd(15)
    t.lt(90)
    t.fd(12.5)
    t.backward(25)
    t.fd(12.5)
    t.penup()
    t.rt(90)
    t.fd(10)
    t.pendown()
    t.lt(90)
    t.fd(12.5)
    t.backward(17.5)
    t.rt(180)
    t.circle(8, 180)
    t.fd(17.5)
    t.penup()
    t.rt(90)
    t.fd(10)
    t.pendown()
    t.rt(90)
    t.fd(25)
    t.lt(90)
    t.penup()
    t.fd(10)
    t.pendown()
    t.circle(6,180)
    t.rt(90)
    t.penup()
    t.fd(14)
    t.lt(90)
    t.pendown()
    t.circle(6.5, 180)
    t.pu()
    t.fd(30)
    t.rt(90)
    t.fd(77.9)
    t.rt(180)
aantalhuizen = int(input("hoeveel huizen wil je? "))
for i in range(aantalhuizen):
    huis()

t.penup()
xboom = random.randint(-600, -400)
t.goto(xboom, -200)
t.pendown()
t.lt(90)
def boom():
    t.seth(90)
    t.color("brown")
    t.fillcolor("brown")
    t.begin_fill()
    vierkant(30)
    t.end_fill()
    t.fd(30)
    t.lt(90)
    t.fd(18)
    t.color("green")
    t.fillcolor("green")
    t.begin_fill()
    for i in range(3):
        t.rt(120)
        t.fd(40)
        t.lt(120)
        t.fd(10)
    for i in range(3):
        t.lt(120)
        t.fd(40)
        t.rt(120)
        t.fd(12) 
    t.end_fill()
    t.penup()
    t.rt(90)
    t.fd(100)
    t.lt(110)
    t.fd(20)
    t.pendown()
    sterretje(7, "yellow", 120)
    t.penup()
    t.lt(90)
    t.fd(131.6)
aantalbomen = int(input("hoeveel bomen wil je? "))
for i in range(aantalbomen):
    boom()

t.penup()
kerstpopje = random.randint(-600, -300)
t.goto(kerstpopje, -250)
def kerstpopje():
  t.color("black")
  t.fillcolor("white")
  t.begin_fill()
  t.seth(0) 
  t.circle(30)
  t.end_fill()
  t.pu()
  t.lt(90)
  t.fd(35)
  t.lt(45)
  t.fd(5)
  t.pd()
  t.fillcolor("blue")
  t.begin_fill()
  t.circle(5)
  t.end_fill()
  t.rt(135)
  t.pu()
  t.fd(10)
  t.pd()
  t.rt(120)
  t.fillcolor("blue")
  t.begin_fill()
  t.circle(5)
  t.end_fill()
  t.pu()
  t.fd(10)
  t.pd()
  t.fd(5)
  t.pu()
  t.fd(5)
  t.rt(60)
  t.pd()
  t.fd(5)
  t.backward(20)
  t.lt(90)
  t.pu()
  t.fd(20) 
  t.pd()
  t.fillcolor("red")
  t.begin_fill()
  for i in range(3):
      t.fd(25)
      t.rt(90)
  t.end_fill()
  t.fillcolor("light blue")
  t.begin_fill()
  t.rt(90)
  t.fd(10)
  t.rt(120)
  t.fd(20)
  t.lt(45)
  for i in range(5):
      t.fd(2)
      t.lt(90)
      t.fd(1)
      t.rt(90)
  t.lt(135)
  t.fd(30)
  t.end_fill()
  t.backward(30)
  t.fillcolor("white")
  t.begin_fill()
  t.circle(5)
  t.end_fill()
  t.pu()
  t.fd(30)
  t.rt(45)
  t.fd(3)
  t.seth(0)
  t.fd(2)
  t.pd()
  t.fillcolor("light blue")
  t.begin_fill()
  for i in range(2):
      t.fd(10)
      t.rt(90)
      t.fd(20)
      t.rt(90)
  t.fd(10)
  for i in range(2):
      t.fd(10)
      t.rt(90)
      t.fd(20)
      t.rt(90)
  t.end_fill()
  t.rt(90)
  t.fd(20)
  t.rt(90)
  t.fillcolor("white")
  t.begin_fill()
  for i in range(2):
      t.fd(20)
      t.lt(90)
      t.fd(10)
      t.lt(90)
  t.end_fill()
  t.rt(180)
  t.fillcolor("white")
  t.begin_fill()
  for i in range(2):
      t.fd(20)
      t.rt(90)
      t.fd(10)
      t.rt(90)
  t.end_fill()
  t.fd(10)
  t.lt(90)
  t.fd(20)
  t.rt(90)
  t.fd(2)
  t.lt(90)
  t.fd(5)
  t.fillcolor("light blue")
  t.begin_fill()
  t.rt(45)
  t.fd(35)
  t.lt(45)
  for i in range(5):
      t.fd(2)
      t.lt(90)
      t.fd(1)
      t.rt(90)
  t.lt(135)
  t.fd(30)
  t.end_fill()
  t.backward(30)
  t.fillcolor("white")
  t.begin_fill()
  t.circle(5)
  t.end_fill()
  t.pu()
  t.rt(90)
  t.fd(60)
  t.lt(60)
  t.fd(10)
  t.rt(105)
  t.pd()
  t.color("red")
  t.fillcolor("white")
  t.begin_fill()
  for i in range(2):
      t.fd(10)
      t.rt(90)
      t.fd(45)
      t.rt(90)
  t.end_fill()
  t.rt(90)
  t.fd(45)
  t.lt(90)
  t.fd(10)
  t.lt(5)
  t.color("black")
  t.fillcolor("red")
  t.begin_fill()
  t.circle(33, 180)
  t.lt(5)
  t.circle(10, 180)
  t.rt(45)
  t.fd(3)
  t.rt(55)
  t.fd(45)
  t.end_fill()
  t.pu()
  t.backward(65)
  t.rt(90)
  t.fd(10)
  t.pd()
  t.fillcolor("white")
  t.begin_fill()
  t.circle(10)
  t.end_fill()
  t.pu()
  t.fd(110)
  t.lt(90)
  t.fd(170)
  t.lt(90)
  t.fd(60)
  t.pd()
aantalkerstpopjes = int(input("hoeveel poppetjes wil je? "))
for i in range(aantalkerstpopjes):
    kerstpopje()
    
t.pu()
xwolk = random.randint(-500, 100)
t.goto(xwolk, 250)
t.pd()
t.seth(0)
t.fillcolor("white")
t.begin_fill()
def wolk(grootte, graden):
  for i in range(4):
    t.circle(grootte, 180)
    t.rt(graden)
  
  t.lt(120)
  t.fd(80)
  t.pu()
  t.fd(150)
aantalwolken = int(input("hoeveel wolken wil je? "))
for i in range(aantalwolken):
    wolk(20, 120)
t.end_fill()

t.pu()
t.goto(310, -310)
t.pd()
def visjes():
    t.fillcolor("light blue")
    t.begin_fill()
    t.circle(20, 450)
    t.end_fill()
    t.rt(60)
    t.fillcolor("orange")
    t.begin_fill()
    for i in range(3):
        t.fd(15)
        t.rt(120)
    t.end_fill()
    t.pu()
    t.backward(30)
    t.rt(90)
    t.fd(10)
    t.pd()
    t.fillcolor("red")
    t.begin_fill()
    t.circle(5)
    t.rt(180)
    t.fd(5)
    t.circle(4)
    t.end_fill()
    t.pu()
    t.fd(40)
    t.rt(150)
    t.fd(15)
    t.pd()
    t.fillcolor("pink")
    t.begin_fill()
    t.circle(4)
    t.end_fill()
    t.pu()
    t.lt(120)
    t.fd(12)
    t.rt(35)
    t.pd()
    t.fillcolor("orange")
    t.begin_fill()
    for i in range(3):
        t.fd(15)
        t.rt(120)
    t.end_fill()
    t.pu()
    t.rt(70)
    t.fd(50)
    t.seth(0)
aantalvisjes = int(input("hoeveel visjes wil je?(max 3) "))
for i in range(aantalvisjes):
    visjes() 

t.pu()
t.goto(-200, -335)
t.pd()
naam = str(input("Wat is jouw naam? "))
t.write("Dit is een tekening voor " + naam, font=("eras", 15, "bold"))